#!/usr/bin/env ruby
# -*- coding: utf-8 -*-
#
# Gyazz2html
#
# % gyazz2html 'masui' 'presen2014'
#
require 'gyazz'
require './foil'

foil = Foil.new

printer_mode = false
while ARGV[0] =~ /^-/ 
  if ARGV[0] == '-p' then
    printer_mode = true
    foil.printer_mode
    ARGV.shift
  elsif ARGV[0] == '-g' then
    ARGV.shift
    foil.gyazzname(ARGV.shift)
  end
end

ARGF.each { |line|
  foil.process line.chomp
}
foil.toc unless printer_mode

foil.close
